name: PR Labeler

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract PR Title and Body
        id: pr_info
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"
          echo "::set-output name=title::$PR_TITLE"
          echo "::set-output name=body::$PR_BODY"

      - name: Add Labels
        run: |
          PR_TITLE=$(echo "$PR_TITLE" | tr '[:upper:]' '[:lower:]')
          PR_BODY=$(echo "$PR_BODY" | tr '[:upper:]' '[:lower:]')
          # Define label patterns and corresponding labels
          
          echo "$PR_TITLE"
          echo "$PR_BODY"
          
          labels=("feature" "fix" "refactor" "build" "docs" "chore")
          
          MATCHED_LABELS=()
          # Iterate over the array elements using a for loop
          for element in "${labels[@]}"; do
            if [[ $PR_TITLE == *"$element"* ]] || [[ $PR_BODY == *"$element"* ]]; then
              MATCHED_LABELS+=("$element")
              echo "The text contains the substring."
              else
              echo "The text does not contain the substring."
            fi
            echo "Element: $element"
          done
            echo "Labels:"
            echo "${MATCHED_LABELS[@]}"
            
          for element in "${MATCHED_LABELS[@]}"; do
            echo "Adding labels '$element' to PR #$PR_NUMBER"
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels" -d "{\"labels\": [\"$element\"]}"
          done
