name: Fetch Release Notes

on:
  release:
    types:
      - published

jobs:
  fetch-and-push-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Fetch Release Notes
        run: |
          gh release view ${{ github.event.release.tag_name }} --repo ${{ github.repository }} --json body -q .body > release-notes.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone Central Repository
        run: git clone https://github.com/Tengizo/release-central.git release-central

      - name: Create and Push Release Notes
        run: |
          cd release-central
          REPO_NAME="${REPO_NAME##*/}"
          mkdir -p $REPO_NAME
          RELEASE_NOTES=$(<../release-notes.txt)
          echo "${RELEASE_NOTES}" > $REPO_NAME/${{ github.event.release.tag_name }}
          git add .
          git commit -m "Add release notes for $REPO_NAME@${{ github.event.release.tag_name }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          REPO_NAME: "${{ github.repository }}"

